### ISSUE TITLE
Unable to replace action bar

### ISSUE THREAD

**Issue by SamRideout** [MicrosoftDocs/xamarin-docs#1377]
I have tried several times to replicate the code in this article but am unable to complete.  I have received an error every time at the stage where you implement "Include the Toolbar Layout".  In particular, the code:  layout="@layout/toolbar"  causes an error immediately with the following message:  
              java.lang.NullPointerException.........  plus 
Indirect rendering enabled
Failed to process message Load
mono.android.DesignerException: java.lang.NullPointerException
	at mono.android.DesignerException.fromThrowable(DesignerException.java:54)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:235)
	at mono.android.DesignerSession.load(DesignerSession.java:314)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:675)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.android.layoutlib.bridge.android.BridgeXmlBlockParser.next(BridgeXmlBlockParser.java:302)
	at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:145)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:900)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:859)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:270)
	at mono.android.DesignerSession.load(DesignerSession.java:307)
	... 4 more

I am using a Dell Inspiron - Intel Core I7 64bit Windows 10 Pro  and Visual Studio Community 2017 version 15.9.5 as of Jan 30, 2019.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077a373a-710a-4514-ba04-dee36309d7b3
* Version Independent ID: f8357c4d-8711-457a-3577-cce29464b51e
* Content: [Replacing the Action Bar - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/tool-bar/replacing-the-action-bar)
* Content Source: [docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by mycral** [comment]
Indirect rendering enabled
Bridge [resources.format] "high_quality" in attribute "breakStrategy" is not a valid integer
Bridge [resources.format] "normal" in attribute "hyphenationFrequency" is not a valid integer
Bridge [resources.format] "high_quality" in attribute "breakStrategy" is not a valid integer
Bridge [resources.format] "normal" in attribute "hyphenationFrequency" is not a valid integer
Failed to process message Load
mono.android.DesignerException: java.lang.NullPointerException
	at mono.android.DesignerException.fromThrowable(DesignerException.java:54)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:235)
	at mono.android.DesignerSession.load(DesignerSession.java:314)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:675)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.android.layoutlib.bridge.android.BridgeXmlBlockParser.next(BridgeXmlBlockParser.java:302)
	at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:145)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:900)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:859)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:270)
	at mono.android.DesignerSession.load(DesignerSession.java:307)
	... 4 more

I have same bug

**Comment by eybbus** [comment]
Having the same problem

**Comment by davidbritch** [comment]
Thanks for submitting an issue and we apologize for the delayed response. The requested updates haven't been made since the creation of the issue, and the timeline for resolution may vary based on resourcing, so the issue is being moved to an internal repo to better track it.
