### ISSUE TITLE
Appears to be Wrong

### ISSUE THREAD

**Issue by adamhill** [MicrosoftDocs/xamarin-docs#1378]
If you add 
#if DEBUG
    [assembly: Application(Debuggable = true)]
#else
     [assembly: Application(Debuggable =false)]
#endif

it will fail with 
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "GenerateJavaStubs" task failed unexpectedly.
System.InvalidOperationException: Application cannot have both a type with an [Application] attribute and an [assembly:Application] attribute.
   at Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(XElement manifest, String applicationClass, List`1 subclasses, List`1 selectedWhitelistAssemblies)
   at Xamarin.Android.Tasks.ManifestDocument.Merge(List`1 subclasses, List`1 selectedWhitelistAssemblies, String applicationClass, Boolean embed, String bundledWearApplicationName, IEnumerable`1 mergedManifestDocuments)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()	PaycorEmployee.Droid			

You have to add:
#if DEBUG
    [Application(Debuggable = true)]
#else
    [Application(Debuggable = false)]
#endif

to the MainApplication.cs in place of the existing [Application]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0056b95-424a-e280-00a9-550a3122a9b7
* Version Independent ID: 120e8039-96cb-9136-0e44-f390c58f2a44
* Content: [Debuggable Attribute - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debuggable-attribute)
* Content Source: [docs/android/deploy-test/debuggable-attribute.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/debuggable-attribute.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @adamhill -- we'll look into this discrepancy and update the docs as required.

**Comment by conceptdev** [comment]
Thanks for this feedback - the page is definitely not clear. Updating now.
