### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by lbreguet** [MicrosoftDocs/xamarin-docs#1904]
When Trying to deploy the app on the emulator I get an unhandled exception: 
```
Unhandled Exception:

System.MissingMethodException: <Timeout exceeded getting exception details>

Mono.Debugger.Soft.InvocationException: Exception of type 'Mono.Debugger.Soft.InvocationException' was thrown.
   at Mono.Debugger.Soft.ObjectMirror.EndInvokeMethodInternalWithResult(IAsyncResult asyncResult) in E:\A\_work\1701\s\external\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\ObjectMirror.cs:line 358
   at Mono.Debugger.Soft.TypeMirror.NewInstance(ThreadMirror thread, MethodMirror method, IList`1 arguments, InvokeOptions options) in E:\A\_work\1701\s\external\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\TypeMirror.cs:line 837
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.CreateValue(EvaluationContext ctx, Object type, Object[] argValues) in E:\A\_work\1701\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 472
   at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitObjectCreateExpression(ObjectCreateExpression objectCreateExpression) in E:\A\_work\1701\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 1081
   at ICSharpCode.NRefactory.CSharp.ObjectCreateExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in E:\A\_work\1701\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\ObjectCreateExpression.cs:line 90
   at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluator.Evaluate(EvaluationContext ctx, String expression, Object expectedType) in E:\A\_work\1701\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluator.cs:line 82
   at Mono.Debugging.Evaluation.ObjectValueAdaptor.GetExpressionValue(EvaluationContext ctx, String exp) in E:\A\_work\1701\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\ObjectValueAdaptor.cs:line 1411
```

It happens in the `App.xaml.cs` file at this location:
```cs
public App()
{
      InitializeComponent();
      MainPage = new NavigationPage(new NotesPage());
}
```

**Comment by conceptdev** [comment]
Please share what docs page you were following, and what operating system, IDE, and platform emulator you were using.

It doesn't seem likely this is a docs problem, and might need to be reported using the **Help > Report a problem** menu item in Visual Studio.

**Comment by lbreguet** [comment]
I fixed the issue by deleting the `bin` and `obj` folders and updating all NuGet packages.
