### ISSUE TITLE
Binding issue with Tizen.NET

### ISSUE THREAD

**Issue by hadihashem** [MicrosoftDocs/xamarin-docs#2675]
Hello
I added a Tizen.NET API v5 platform project and I get the following exception when starting the App:
System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
 ---&gt; System.Exception: This is the 'bait'.  You probably need to add one of the SQLitePCLRaw.bundle_* nuget packages to your platform project.
   at SQLitePCL.Batteries_V2.Init()
   at SQLite.SQLiteConnection..cctor()
   --- End of inner exception stack trace ---
   at SQLite.SQLiteConnection..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionPool.Entry.Connect()
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString)
   at SQLite.SQLiteAsyncConnection.GetConnection()
   at SQLite.SQLiteAsyncConnection.get_TableMappings()
   at Todo.TodoItemDatabase.InitializeAsync()
   at Todo.TaskExtensions.SafeFireAndForget(Task task, Boolean returnToCallingContext, Action`1 onException)
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__139_0(Object state)
   at Tizen.Applications.TizenSynchronizationContext.&lt;&gt;c__DisplayClass1_0.&lt;Post&gt;b__0()
   at Tizen.Applications.TizenSynchronizationContext.GSourceManager.Handler(IntPtr userData)
   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)
   at Todo.Tizen.Program.Main(String[] args) in ...
Can you please help me to solve it?
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @hadihashem 

Looks like you need to add the SQLite NuGet package to your Tizen project.

**Comment by hadihashem** [comment]
Hi @davidbritch 
Sorry but this did not fix the problem
A TypeInitializationException is still showing
Please advise
Regards

```
System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
 ---> System.Exception: This is the 'bait'.  You probably need to add one of the SQLitePCLRaw.bundle_* nuget packages to your platform project.
   at SQLitePCL.Batteries_V2.Init()
   at SQLite.SQLiteConnection..cctor()
   --- End of inner exception stack trace ---
   at SQLite.SQLiteConnection..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionPool.Entry.Connect()
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString)
   at SQLite.SQLiteAsyncConnection.GetConnection()
   at SQLite.SQLiteAsyncConnection.get_TableMappings()
   at Todo.TodoItemDatabase.InitializeAsync()
   at Todo.TaskExtensions.SafeFireAndForget(Task task, Boolean returnToCallingContext, Action`1 onException)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Tizen.Applications.TizenSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at Tizen.Applications.TizenSynchronizationContext.GSourceManager.Handler(IntPtr userData)
   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)
   at Todo.Tizen.Program.Main(String[] args) in ...
```

**Comment by davidbritch** [comment]
Hi @hadihashem 

As the error suggests, you need to add one of the SQLitePCLRaw.bundle_* nuget packages to your platform project.

**Comment by hadihashem** [comment]
Hi @davidbritch 
I'm afraid after adding the mentionned package, the App will simply crash without any exception or error message
Please see example attached
Regards
[Todo.zip](https://github.com/MicrosoftDocs/xamarin-docs/files/4402337/Todo.zip)

**Comment by davidbritch** [comment]
Hi @hadihashem 

This is something you'll have to take up with Samsung, who develop the Tizen platform. See https://docs.microsoft.com/xamarin/xamarin-forms/platform/other/tizen for more info.
