### ISSUE TITLE
Linked Nugetizer 3000 VSIX Installer is Broken (MissingPackagePart)

### ISSUE THREAD

**Issue by dfoulk** [MicrosoftDocs/xamarin-docs#743]
http://bit.ly/nugetizer-2017 links to an installer that throws the following exception:

Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException: Exception of type 'Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException' was thrown.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.InitializeNestedExtension(ZipPackage parentVSIX, IExtensionReference reference, Func`2 initialize)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.InitializeNestedExtensions()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisitesInternal(IInstallableExtension extension, ICollection`1 installedPackages, ICollection`1 installablePackages, ICollection`1 unresolvedReferences)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisites(IInstallableExtension extension, IEnumerable`1& installedPackages, IEnumerable`1& installablePackages, IEnumerable`1& unresolvedReferences)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44cfe14b-198c-56d5-0b63-de00dd08bafe
* Version Independent ID: 39eea43d-d7b5-1659-1583-dc23d099c9f8
* Content: [NuGet Multiplatform Library Projects (aka Nugetizer 3000) - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/nuget-multiplatform-libraries/?tabs=windows)
* Content Source: [docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
We are aware of an issue that is causing installer failures, and are working to mitigate and resolve. Thanks for the heads-up; we hope to be back online soon.
